config/routes.rb
Rails.application.routes.draw do
  get 'record/index'
  get 'treco_diet2/treco_diet_select'
  get 'treco_bulkup2/treco_bulkup_select'
#トレーニング記録
  get 'treco_main/treco_record'
  get 'treco_main/new'
  get 'treco_main/index'
  #post 'treco_main/new'
  post 'treco_main/index'
  get 'treco_main/create'
  post 'treco_main/create'
  get 'treco_main/search'
  post 'treco_main/search'

#トレーニング記録一覧（日付）
  get 'treco_main/treco_record_list'
#トレーニング記録一覧（詳細）
  get 'treco_main/treco_record_list2'  
#ホーム画面選択（ダイエット・バルクアップ）
  get 'treco_main/treco_main_select'
  get 'treco_main/treco_others'
  get 'user_managementse/treco_diet_main2'
#トレーニング部位選択
  get 'treco_diet2/treco_diet_reg'
  get 'treco_diet2/treco_diet_hip'
  get 'treco_diet2/treco_diet_back'
  get 'treco_diet2/treco_diet_chest'
  get 'treco_diet2/treco_diet_arm'
  get 'treco_diet2/treco_diet_shoulder'
  get 'treco_diet2/treco_diet_stomach'

  get 'treco_bulkup2/treco_bulkup_reg'
  get 'treco_bulkup2/treco_bulkup_hip'
  get 'treco_bulkup2/treco_bulkup_back'
  get 'treco_bulkup2/treco_bulkup_chest'
  get 'treco_bulkup2/treco_bulkup_arm'
  get 'treco_bulkup2/treco_bulkup_shoulder'
  get 'treco_bulkup2/treco_bulkup_stomach'
#脚
  get 'treco_diet2/treco_diet_regpress'
  get 'treco_diet2/treco_diet_regpress2'
  get 'treco_diet2/treco_diet_ad'
  get 'treco_diet2/treco_diet_regextension'
  get 'treco_diet2/treco_diet_regcarl'

  get 'treco_bulkup2/treco_bulkup_regpress'
  get 'treco_bulkup2/treco_bulkup_regpress2'
  get 'treco_bulkup2/treco_bulkup_ad'
  get 'treco_bulkup2/treco_bulkup_regextension'
  get 'treco_bulkup2/treco_bulkup_regcarl'
#お尻
  get 'treco_diet2/treco_diet_ab'

  get 'treco_bulkup2/treco_bulkup_ab'
#背中
  get 'treco_diet2/treco_diet_latpull'
  get 'treco_diet2/treco_diet_latpull2'
  get 'treco_diet2/treco_diet_seatedrow'

  get 'treco_bulkup2/treco_bulkup_latpull'
  get 'treco_bulkup2/treco_bulkup_latpull2'
  get 'treco_bulkup2/treco_bulkup_seatedrow'
#胸
  get 'treco_diet2/treco_diet_chestpress'
  get 'treco_diet2/treco_diet_incline_chestpress'

  get 'treco_bulkup2/treco_bulkup_chestpress'
  get 'treco_bulkup2/treco_bulkup_incline_chestpress'
#腕
  get 'treco_diet2/treco_diet_bicepscurl'

  get 'treco_bulkup2/treco_bulkup_bicepscurl'
#肩
  get 'treco_diet2/treco_diet_shoulderpress'
  get 'treco_diet2/treco_diet_reardelt'

  get 'treco_bulkup2/treco_bulkup_shoulderpress'
  get 'treco_bulkup2/treco_bulkup_reardelt'
#お腹
  get 'treco_diet2/treco_diet_ab_crunch'
  get 'treco_diet2/treco_diet_torso_rotation'
  get 'treco_diet2/treco_diet_decline_situp'

  get 'treco_bulkup2/treco_bulkup_ab_crunch'
  get 'treco_bulkup2/treco_bulkup_torso_rotation'
  get 'treco_bulkup2/treco_bulkup_decline_situp'

  devise_for :users

  resources :treco_main, only: [:create, :new]
  
  resources :treco_main
  resources :treco_diet2

end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"　

app/controllers/treco_main_controller.rb
class TrecoMainController < ApplicationController
  
  
##

def treco_record_list
    #@tranings = Traning.all
    @tranings = Traning.where(user_id: current_user.id)

    #ログイン中のユーザーデーターのみ表示する記述
    #if user_signed_in?

    #Userテーブルの左外部にTraningテーブルを結合
    #@traning = User.left_joins(:traning).where(name: current_user.name).order(created_at: :desc).limit(7)



@traning = Traning.limit(5).where(user_id: current_user.id).order(id: "DESC")

     #@user = User.find(params[:id])
# ===============追加==============
    #@traning = @user.tranings

    #@traning = Traning.order(created_at: :desc).limit(7)
    #@traning = User.where(name: current_user.name).order(created_at: :desc).limit(7)
    #end

   end

  def search
   # @tranings = Traning
   @tranings = Traning.where(user_id: current_user.id)

    @traning = Traning.new(traning_params)
    if @traning.created_at.present?
      @traning = Traning.where(user_id: current_user.id).where(created_at: "#{@traning.created_at}".in_time_zone.all_day).order(id: "DESC")
    else
      @traning = Traning.none
    end
      render :treco_record_list
  end


  def traning_params
   params.require(:traning).permit(:bodypart_menu,:weight_1set,:weight_2set,:weight_3set,:weight_4set,
    :weight_5set,:weight_6set,:weight_7set,:reps_1set,:reps_2set,:reps_3set,:reps_4set,
    :reps_5set,:reps_6set,:reps_7set,:created_at)
  end

  def treco_main_select
  end

  def treco_others
  end

  def treco_record
    @tranings = Traning.new

    #1つ前のページをセッションに保存する
    #session[:previous_url] = request.referer 
  end

  def treco_record_list2
    @tranings = Traning.all
    #render :treco_record_list
  end

def new
  end

def create
  @traning = Traning.new(tranings_params)

  @traning.user_id = current_user.id 
  
  @traning.save

  redirect_to treco_main_treco_record_list_path 

  #session[:previous_url] ←#セッションに保存されたページにリダイレクトするコード
  #redirect_back(fallback_location: treco_main_treco_record_path)
end

private
def tranings_params
  params.require(:traning).permit(:bodypart_menu,:weight_1set,:weight_2set,:weight_3set,:weight_4set,
    :weight_5set,:weight_6set,:weight_7set,:reps_1set,:reps_2set,:reps_3set,:reps_4set,
    :reps_5set,:reps_6set,:reps_7set)#.merge(user_id: current_user.id)
end

end

app/helpers/treco_main_helper.rb
module TrecoMainHelper
end

app/views/treco_main/create.html.erb
<h1>create</h1>
<% @tranings.each do |traning| %>
 <%= traning.bodypart_menu %><br>
 <%= traning.weight %>
 <%= traning.reps %>
<% end %>

app/views/treco_main/index.html.erb
<h1>index</h1>

<% @user_managements.each do |user_management| %>
 <p>部位</p>
 <%= user_management.name %><br>
 <p>種目</p>
 <%= user_management.email %><br>
 <p>セット数</p>
 <%= user_management.password %>
<% end %>

app/views/treco_main/new.html.erb
<h1>登録</h1>
<%= form_with model: @user_managements,url: treco_main_create_path do |form| %>
  <div>
    <%= form.label :部位 %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :種目 %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :セット数 %>
    <%= form.text_field :password %>
    
    <%= form.select :password,[["a", 1],["b", 2],["c", 3]], { selected: 2 } %>
  </div>
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/treco_main/search.html.erb
<h1>search</h1>

<div class="item-box">  
<% @traning.each do |latest_bodyrecord| %>
  <div class="latest-box">
    <table class="latest-body-data">
      <tbody>
          <tr>
            <th class="latest-data">日付</th>
            <td class="latest-value"><%= l latest_bodyrecord.created_at %></td>
          </tr>
      </tbody>
    </table>
  </div>
  <% end %>
</div>

app/views/treco_main/treco_main_select.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_main', :media => "all" %>

<div id="main2_container">


<%# ログイン中のユーザー名を表示する記述（コメントアウト中）%>
<%#<% if user_signed_in? %>
<!-- <p>ユーザー名：<%#<%= current_user.name %></p> -->
<%#<% end %>


<h2 class="main2_button" style="font-weight:bold;text-decoration:underline;">目的を選択してください</h2>  
<h2 class="main2_button"><%= link_to "ダイエット 脂肪燃焼をする", treco_diet2_treco_diet_select_path  %></h2>
<h2 class="main2_button"><%= link_to "バルクアップ 筋肉増量をする", treco_bulkup2_treco_bulkup_select_path %></h2>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_main/treco_others.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_others', :media => "all" %>

<div id="all_container">    
<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<h2 id="others">その他</h2>
<ul id="others-content">
<li class="others-item"><a class="others-item-link" href="">お問い合わせ</a></li>
<li class="others-item"><a class="others-item-link" href="">プライバシーポリシー</a></li>
<li class="others-item"><%= link_to 'ログアウト',destroy_user_session_path,class: 'others-item-link',method: :delete %></li>
</ul>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_main/treco_record.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_record', :media => "all" %>

<div id="all_container">
<div id="record-container">
<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>

<h2>トレーニング部位・種目名
<%= form_with model: @tranings,local: true,url: treco_main_create_path do |form| %>
<%= form.select :bodypart_menu,
[["【太もも】45度レッグプレス", "【太もも】45度レッグプレス"],
["【太もも】レッグプレス", "【太もも】レッグプレス"],
["【太もも】アダクター", "【太もも】アダクター"],
["【太もも】レッグエクステンション", "【太もも】レッグエクステンション"],
["【太もも】ライイングレッグカール", "【太もも】ライイングレッグカール"],
["【お尻】アブダクター", "【お尻】アブダクター"],
["【背中】フロントラットプルダウン", "【背中】フロントラットプルダウン"],
["【背中】バックラットプルダウン", "【背中】バックラットプルダウン"],
["【背中】シーテッドローイング", "【背中】シーテッドローイング"],
["【胸】チェストプレス", "【胸】チェストプレス"],
["【胸】インクラインチェストプレス", "【胸】インクラインチェストプレス"],
["【腕】バイセップスカール（力こぶ）", "【腕】バイセップスカール（力こぶ）"],
["【肩】ショルダープレス", "【肩】ショルダープレス"],
["【肩】リアデルトイドフライ", "【肩】リアデルトイドフライ"],
["【お腹】アブドミナルクランチ", "【お腹】アブドミナルクランチ"],
["【お腹】トーソーローテーション", "【お腹】トーソーローテーション"],
["【お腹】デクラインシットアップベンチ", "【お腹】デクラインシットアップベンチ"]],{ prompt: false },class: 'item' %>
</h2>

<h2>セット数・重量・回数
<p class="record-content">1セット目<%= form.text_field :weight_1set,class: 'content-set' %>kg<%= form.text_field :reps_1set,class: 'content-set' %>回</p>
<p class="record-content">2セット目<%= form.text_field :weight_2set,class: 'content-set' %>kg<%= form.text_field :reps_2set,class: 'content-set' %>回</p>

<p class="record-content">3セット目<%= form.text_field :weight_3set,class: 'content-set' %>kg<%= form.text_field :reps_3set,class: 'content-set' %>回</p>
<p class="record-content">4セット目<%= form.text_field :weight_4set,class: 'content-set' %>kg<%= form.text_field :reps_4set,class: 'content-set' %>回</p>
<p class="record-content">5セット目<%= form.text_field :weight_5set,class: 'content-set' %>kg<%= form.text_field :reps_5set,class: 'content-set' %>回</p>
<p class="record-content">6セット目<%= form.text_field :weight_6set,class: 'content-set' %>kg<%= form.text_field :reps_6set,class: 'content-set' %>回</p>
<p class="record-content">7セット目<%= form.text_field :weight_7set,class: 'content-set' %>kg<%= form.text_field :reps_7set,class: 'content-set' %>回</p></h2>

<p><%= form.submit "記録する",id: 'record-btn' %></p>
<% end %>
</div>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_main/treco_record_list.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_record_list', :media => "all" %>

<div id="all_container">
<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>


<h2>トレーニング記録一覧</h2>

<%= form_with model: @tranings,local: true,url: treco_main_search_path do |form| %>
      <h3>見たい日付を選択してください</h3>
<%= form.date_field :created_at,class: 'item' %><br>
<%= form.submit "確認する",id: 'check-btn' %>
    <% end %>

  <div id="record-list-container">
<% @traning.each do |traning_records| %>
    <table>
      <tbody>
          <tr>
            <th class="record-head">日付</th>
            <td class="record-item"><%= l traning_records.created_at %></td>
          </tr>
　　　　　　<tr>
            <th class="record-head">部位・種目</th>
            <td class="record-item"><%= traning_records.bodypart_menu %></td>
          </tr>
          <tr>
            <th class="record-head">【1セット目】重量・回数</th>
            <td class="record-item"><%= traning_records.weight_1set %>kg・<%= traning_records.reps_1set %>回</td>
          </tr>
          <tr>
          	<th class="record-head">【2セット目】重量・回数</th>
            <td class="record-item"><%= traning_records.weight_2set %>kg・<%= traning_records.reps_2set %>回</td>
          </tr>
          <tr>
          	<th class="record-head">【3セット目】重量・回数</th>
            <td class="record-item"><%= traning_records.weight_3set %>kg・<%= traning_records.reps_3set %>回</td>
          </tr>
          <tr>
          	<th class="record-head">【4セット目】重量・回数</th>
            <td class="record-item"><%= traning_records.weight_4set %>kg・<%= traning_records.reps_4set %>回</td>
          </tr>
          <tr>
          	<th class="record-head">【5セット目】重量・回数</th>
            <td class="record-item"><%= traning_records.weight_5set %>kg・<%= traning_records.reps_5set %>回</td>
          </tr>
          <tr>
          	<th class="record-head">【6セット目】重量・回数</th>
            <td class="record-item"><%= traning_records.weight_6set %>kg・<%= traning_records.reps_6set %>回</td>
          </tr>
          <tr>
          	<th class="record-head">【7セット目】重量・回数</th>
            <td class="record-item"><%= traning_records.weight_7set %>kg・<%= traning_records.reps_7set %>回</td>
          </tr>
      </tbody>
    </table>
<% end %>
</div>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_main/treco_record_list2.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_record_list', :media => "all" %>


<div id="all_container">
<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<h2>トレーニング記録一覧</h2>

<% @tranings.each do |traning| %>
 <%= l traning.created_at %><br>
 <%= traning.bodypart_menu %>
 <%= traning.weight_1set %>
 <%= traning.reps_1set %>
 <%= traning.weight_2set %>
 <%= traning.reps_2set %>
 <%= traning.weight_3set %>
 <%= traning.reps_3set %>
 <%= traning.weight_4set %>
 <%= traning.reps_4set %>
 <%= traning.weight_5set %>
 <%= traning.reps_5set %>
 <%= traning.weight_6set %>
 <%= traning.reps_6set %>
 <%= traning.weight_7set %>
 <%= traning.reps_7set %>
<% end %>

<!-- おそらくrubyでDBからデータを取得して、自動で一覧表示させる-->   
</div>