config/routes.rb
Rails.application.routes.draw do
  get 'record/index'
  get 'treco_diet2/treco_diet_select'
  get 'treco_bulkup2/treco_bulkup_select'
#トレーニング記録
  get 'treco_main/treco_record'
  get 'treco_main/new'
  get 'treco_main/index'
  #post 'treco_main/new'
  post 'treco_main/index'
  get 'treco_main/create'
  post 'treco_main/create'
  get 'treco_main/search'
  post 'treco_main/search'

#トレーニング記録一覧（日付）
  get 'treco_main/treco_record_list'
#トレーニング記録一覧（詳細）
  get 'treco_main/treco_record_list2'  
#ホーム画面選択（ダイエット・バルクアップ）
  get 'treco_main/treco_main_select'
  get 'treco_main/treco_others'
  get 'user_managementse/treco_diet_main2'
#トレーニング部位選択
  get 'treco_diet2/treco_diet_reg'
  get 'treco_diet2/treco_diet_hip'
  get 'treco_diet2/treco_diet_back'
  get 'treco_diet2/treco_diet_chest'
  get 'treco_diet2/treco_diet_arm'
  get 'treco_diet2/treco_diet_shoulder'
  get 'treco_diet2/treco_diet_stomach'

  get 'treco_bulkup2/treco_bulkup_reg'
  get 'treco_bulkup2/treco_bulkup_hip'
  get 'treco_bulkup2/treco_bulkup_back'
  get 'treco_bulkup2/treco_bulkup_chest'
  get 'treco_bulkup2/treco_bulkup_arm'
  get 'treco_bulkup2/treco_bulkup_shoulder'
  get 'treco_bulkup2/treco_bulkup_stomach'
#脚
  get 'treco_diet2/treco_diet_regpress'
  get 'treco_diet2/treco_diet_regpress2'
  get 'treco_diet2/treco_diet_ad'
  get 'treco_diet2/treco_diet_regextension'
  get 'treco_diet2/treco_diet_regcarl'

  get 'treco_bulkup2/treco_bulkup_regpress'
  get 'treco_bulkup2/treco_bulkup_regpress2'
  get 'treco_bulkup2/treco_bulkup_ad'
  get 'treco_bulkup2/treco_bulkup_regextension'
  get 'treco_bulkup2/treco_bulkup_regcarl'
#お尻
  get 'treco_diet2/treco_diet_ab'

  get 'treco_bulkup2/treco_bulkup_ab'
#背中
  get 'treco_diet2/treco_diet_latpull'
  get 'treco_diet2/treco_diet_latpull2'
  get 'treco_diet2/treco_diet_seatedrow'

  get 'treco_bulkup2/treco_bulkup_latpull'
  get 'treco_bulkup2/treco_bulkup_latpull2'
  get 'treco_bulkup2/treco_bulkup_seatedrow'
#胸
  get 'treco_diet2/treco_diet_chestpress'
  get 'treco_diet2/treco_diet_incline_chestpress'

  get 'treco_bulkup2/treco_bulkup_chestpress'
  get 'treco_bulkup2/treco_bulkup_incline_chestpress'
#腕
  get 'treco_diet2/treco_diet_bicepscurl'

  get 'treco_bulkup2/treco_bulkup_bicepscurl'
#肩
  get 'treco_diet2/treco_diet_shoulderpress'
  get 'treco_diet2/treco_diet_reardelt'

  get 'treco_bulkup2/treco_bulkup_shoulderpress'
  get 'treco_bulkup2/treco_bulkup_reardelt'
#お腹
  get 'treco_diet2/treco_diet_ab_crunch'
  get 'treco_diet2/treco_diet_torso_rotation'
  get 'treco_diet2/treco_diet_decline_situp'

  get 'treco_bulkup2/treco_bulkup_ab_crunch'
  get 'treco_bulkup2/treco_bulkup_torso_rotation'
  get 'treco_bulkup2/treco_bulkup_decline_situp'

  devise_for :users

  resources :treco_main, only: [:create, :new]
  
  resources :treco_main
  resources :treco_diet2

end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"　

app/controllers/treco_bulkup2_controller.rb
class TrecoBulkup2Controller < ApplicationController

def treco_bulkup_select
  end



  def treco_bulkup_reg
  end

  def treco_bulkup_hip
  end
  
  def treco_bulkup_back
  end

  def treco_bulkup_chest
  end

  def treco_bulkup_arm
  end

  def treco_bulkup_shoulder
  end

  def treco_bulkup_stomach
  end

#脚
  def treco_bulkup_regpress
  end

  def treco_bulkup_regpress2
  end

  def treco_bulkup_ad
  end

  def treco_bulkup_regextension
  end

  def treco_bulkup_regcarl
  end

#お尻
  def treco_bulkup_ab
  end
  
#背中
  def treco_bulkup_latpull
  end

  def treco_bulkup_latpull2
  end

  def treco_bulkup_seatedrow
  end

#胸
  def treco_bulkup_chestpress
  end

  def treco_bulkup_incline_chestpress
  end

#腕
  def treco_bulkup_bicepscurl
  end

#肩
  def treco_bulkup_shoulderpress
  end

  def treco_bulkup_reardelt
  end

#お腹
  def treco_bulkup_ab_crunch
  end

  def treco_bulkup_torso_rotation
  end

  def treco_bulkup_decline_situp
  end

end

app/helpers/treco_bulkup2_helper.rb
module TrecoBulkup2Helper
end

app/views/treco_bulkup2/treco_bulkup_ad.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_method', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>アダクター</h2>
<p><%= image_tag 'diet_button_abad.jpg',class: 'machine_img' %></p>
<h3>やり方</h3>
<p>1. 1 ピンを差して重りを調節します。</p>
<p>2. 椅子に座り、ももが床と平行になるように足位置を調整します。</p>
<p>3. プルピン（引く）を使いスタート時の足の位置を調節。</p>
<p>4. ハンドルを握り、ゆっくりと膝を中心へ寄せます。</p>
<p>5. 膝を外へゆっくりと戻します。</p>
<p>6. 背中上部がパッドから離れないように注意しましょう。</p>
<iframe id="traning-movie" width="560" height="315" src="https://www.youtube.com/embed/uS3wHUEKIAk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_back.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_reg', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_reg_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>背中のトレーニングマシンを選択する</h2>
<ul id="diet_reg_button_container">
<!--マシンの画像を挿入して3つずつ横並びにする-->
<li class="diet_reg_button"><%= link_to image_tag("diet_button_latpull.jpg",class: 'reg_machine'),treco_bulkup2_treco_bulkup_latpull_path %></li>
<br>
<li class="diet_reg_button"><%= link_to image_tag("diet_button_latpull.jpg",class: 'reg_machine'),treco_bulkup2_treco_bulkup_latpull2_path %></li>
<br>
<li class="diet_reg_button"><%= link_to image_tag("diet_button_seatedrow.jpg",class: 'reg_machine'),treco_bulkup2_treco_bulkup_seatedrow_path %></li>
</ul>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_bicepscurl.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_method', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>バイセップスカール（力こぶ）</h2>
<p><%= image_tag 'diet_button_bicepscurl.jpg',class: 'machine_img' %></p>
<h3>やり方</h3>
<p>1. 肘をマシンの回転軸の真横に置いた時に、二の腕が全てシートにつく高さにイスを調節します。</p>
<p>2. ピンで重りを調節します。</p>
<p>3. グリップを握り、シートにつけた二の腕と肘が浮かないように腕を体側に曲げます</p>
<p>4. 重りが下につく直前まで、ゆっくりと元の状態まで戻します。</p>

<iframe id="traning-movie" src="https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2FAF.gifuena%2Fvideos%2F511816336881861%2F&show_text=false&width=476&t=0" width="476" height="476" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_chestpress.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_method', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>チェストプレス</h2>
<p><%= image_tag 'diet_button_chestpress.jpg',class: 'machine_img' %></p>
<h3>やり方</h3>
<p>1. 胸のトップと手の高さが同じになるようにイスを調節します。</p>
<p>2. ピンで重りを調節します。</p>
<p>3. 胸を張った状態でグリップを握ります。</p>
<p>4. 肘を伸ばしきらないようバーを体の前に押し出します。</p>
<p>5. 重りが下につく直前までゆっくり戻します。</p>

<iframe id="traning-movie" width="560" height="315" src="https://www.youtube.com/embed/zF5-eZg9Y4s" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_decline_situp.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_method', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>デクラインシットアップベンチ</h2>
<p><%= image_tag 'diet_button_decline_situp.jpg',class: 'machine_img' %></p>
<h3>やり方</h3>
<p>1. ベンチの先にあるパッドの間に足を引っ掛けて寝転ぶ</p>
<p>2. 両手を頭の後ろにおく</p>
<p>3. 頭と背中を丸めるようにして、体を起こす</p>
<p>4. 体全体がベンチに少しつく程度までゆっくりと戻す</p>

<iframe id="traning-movie" width="560" height="315" src="https://www.youtube.com/embed/usUrULQIKuA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_hip.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_reg', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_reg_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>お尻のトレーニングマシンを選択する</h2>
<ul id="diet_reg_button_container">
<!--マシンの画像を挿入して3つずつ横並びにする-->
<li class="diet_reg_button"><%= link_to image_tag("diet_button_abad.jpg",class: 'reg_machine'),treco_bulkup2_treco_bulkup_ab_path %></li>
</ul>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_incline_chestpress.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_method', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>インクラインチェストプレス</h2>
<p><%= image_tag 'diet_button_incline_chestpress.jpg',class: 'machine_img' %></p>
<h3>やり方</h3>
<p>1. グリップが胸の真ん中にくるよようにイスの高さを調節します。</p>
<p>2. 重りのプレートをバー横の棒にはめ込む。</p>
<p>3. 胸を張った状態でグリップを握ります。</p>
<p>4. 肘を伸ばしきらないようバーを体の前に押し出します。</p>
<p>5. バーがマシン本体につく直前までゆっくり戻します。</p>

<iframe id="traning-movie" src="https://www.facebook.com/plugins/video.php?height=476&href=https%3A%2F%2Fwww.facebook.com%2Fanytimefitness.shimokitazawa%2Fvideos%2F434230054174945%2F&show_text=false&width=476&t=0" width="476" height="476" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_reardelt.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_method', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>リアデルトイドフライ</h2>
<p><%= image_tag 'diet_button_pec_reardelt.jpg',class: 'machine_img' %></p>
<h3>やり方</h3>
<p>1. バーを一番内側に調節します。</p>
<p>2. ピンで重さを調節します。</p>
<p>3. 手の平を下にして内側のグリップを握ります。</p>
<p>4. グリップを握った腕と地面が平行になるように、イスの高さを調節します。</p>
<p>5. 腕が一直線になる位置までゆっくり外に開きます。</p>
<p>6. 重りが下につく直前までゆっくり戻します。</p>

<iframe id="traning-movie" width="560" height="315" src="https://www.youtube.com/embed/PjmJUeBGVmY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>

app/views/treco_bulkup2/treco_bulkup_regcarl.html.erb
<!-- スタイルシート -->
<%= stylesheet_link_tag 'treco_diet_method', :media => "all" %>

<p id="return-btn"><a id="return-btn-link" href=""onclick="window.history.back(); return false;">戻る</a></p>
<div id="all_container">
<h2 id="diet_title">バルクアップ(筋肉増量)をする</h2>

<h3>筋肉量を増やすためのトレーニング目安</h3>
<p>まずは8〜12回の反復運動で限界と感じる重さに設定し、<br>
各種目で2〜3セットのトレーニングを行ってみましょう</p>
<h2>ライイングレッグカール</h2>
<p><%= image_tag 'diet_button_regcarl.jpg',class: 'machine_img' %></p>
<h3>やり方</h3>
<p>1. レッグカールのベンチに深く座る</p>
<p>2. 重さを調整する</p>
<p>3. パット部分に足を置く</p>
<p>4. 上のパットを太ももに触れる程度まで下げる</p>
<P>5. 両手で前または横にあるバーを軽く掴む</p>
<P>6. つま先をまっすぐにする</p>
<P>7. 勢いをつけず脚を下げていく</p>
<P>8. 重りが下につく直前まで下げたら、ゆっくりと元に戻す</p>

<iframe id="traning-movie" width="560" height="315" src="https://www.youtube.com/embed/mAW5MHRzVpI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<nav id="nav-container">
<ul id="global-nav">
<li class="nav-item"><%= image_tag 'nav_home.png',class: 'nav-item-icon' %><br><%= link_to "ホーム", treco_main_treco_main_select_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_calendar.png',class: 'nav-item-icon' %><br><%= link_to "記録一覧", treco_main_treco_record_list_path,class: 'nav-item-link'  %></li>

<li class="nav-item"><%= image_tag 'nav_record.png',class: 'nav-item-icon' %><br><%= link_to "記録する", treco_main_treco_record_path,class: 'nav-item-link' %></li>

<li class="nav-item"><%= image_tag 'nav_others.png',class: 'nav-item-icon' %><br><%= link_to "その他", treco_main_treco_others_path,class: 'nav-item-link' %></li>
</ul>
</nav>